FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

RUN pip install --no-cache-dir \
    matplotlib \
    torchvision \
    tqdm \
    scikit-learn

WORKDIR /app
COPY . /app

CMD ["python", "mae_cifar10.py", "pretrain"]